.PHONY: clean All

All:
	@echo "----------Building project:[ pricers - Debug ]----------"
	@"$(MAKE)" -f  "pricers.mk"
clean:
	@echo "----------Cleaning project:[ pricers - Debug ]----------"
	@"$(MAKE)" -f  "pricers.mk" clean
