.PHONY: clean All

All:
	@echo "----------Building project:[ HW11_FD - Debug ]----------"
	@cd "HW11_FD" && "$(MAKE)" -f  "HW11_FD.mk"
clean:
	@echo "----------Cleaning project:[ HW11_FD - Debug ]----------"
	@cd "HW11_FD" && "$(MAKE)" -f  "HW11_FD.mk" clean
